public class Main {
    public static void main(String[] args) {
        int age = 19;
        String name = "Tekraj";
        double height = 5.9;
        boolean isStudent = true;
        char grade = 'A';

        System.out.println("My age: " + age);
        System.out.println("My name: " + name);
        System.out.println("My height: " + height);
        System.out.println("Am I a student: " + isStudent);
        System.out.println("My grade: " + grade);
    }
}
